<?php 
		
	DEFINE("DB_NAME",'jil_event');
	DEFINE("DB_USER",'root');
	DEFINE("DB_PASS",'');
	DEFINE("DB_HOST",'localhost');

	DEFINE('USER_CREATED', 101);
	DEFINE('USER_EXISTS', 102);
	DEFINE('USER_FAILED', 103);

	DEFINE('USER_VERIFIED', 201);
	DEFINE('USER_NULL', 202);
	DEFINE('USER_PASS_ERR', 203);

	DEFINE('USER_LOGOUT', 301);
	DEFINE('USER_LOGOUT_ERR', 302);

	DEFINE('FEEDBACK_SUCCESS', 401);
	DEFINE('FEEDBACK_ERR', 402);

 ?>